# Generated by Django 2.1.5 on 2019-02-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttestatEge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestat', models.CharField(default=None, max_length=20, null=True)),
                ('middle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ege', models.CharField(default=None, max_length=20, null=True)),
                ('lesson', models.CharField(default=None, max_length=20, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student')),
            ],
            options={
                'verbose_name': 'Аттестат и ЕГЕ студента',
                'verbose_name_plural': 'Аттестаты и ЕГЕ студентов',
            },
        ),
        migrations.CreateModel(
            name='StudentPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(default=None, max_length=20, null=True)),
                ('region', models.TextField(default=None, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student')),
            ],
            options={
                'verbose_name': 'Паспорт студента',
                'verbose_name_plural': 'Паспорта студентов',
            },
        ),
    ]
