# Generated by Django 2.1.5 on 2019-02-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_studentattestatege_studentpassport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default=None, max_length=100)),
                ('talk', models.BooleanField(default=False)),
                ('result', models.IntegerField(default=0)),
                ('payment', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=0)),
                ('contract_bool', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Contract')),
                ('registar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Specialities'),
        ),
    ]
