# Generated by Django 2.1.5 on 2019-02-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Контаркт', 'verbose_name_plural': 'Контаркты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='specialities',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
    ]
