# Generated by Django 2.1.5 on 2019-02-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentattestatege_studentpassport'),
        ('company', '0003_auto_20190202_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student'),
        ),
    ]
